# Generated by Django 2.2 on 2020-09-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('subtitle', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
